version: "3"

services:
  minecraft:
    image: minecraft:latest
    ports:
      - "19132:19132/udp"
      - "25565:25565"
    volumes:
      - /opt/minecraft/worlds:/app/server/worlds
      - /opt/minecraft/logs:/app/server/logs
      - /opt/minecraft/dynmap:/app/server/plugins/dynmap